dify:
  api_key: "app-ETj32anudzJTI01qLQJoE8H5"  # Dify API密钥
  endpoint: "http://localhost/v1"  # Dify API端点
  default_user: "bailing"
  settings:
    temperature: 0.7
    top_p: 0.9
    max_tokens: 2000
    presence_penalty: 0
    frequency_penalty: 0
  stream:
    enabled: true
    chunk_size: 20
  retry:
    max_retries: 3
    retry_interval: 1  # 秒
  timeout:
    connect: 10  # 秒
    read: 30    # 秒 