llm:
  # 默认使用的LLM提供商
  default_provider: "openai"
  
  # OpenAI配置
  openai:
    model_name: "gpt-3.5-turbo"
    api_key: "your-api-key"
    url: "https://api.openai.com/v1"
    
  # DeepSeek配置
  deepseek:
    model_name: "deepseek-chat"
    api_key: "your-api-key"
    url: "https://api.deepseek.com/v1"
    temperature: 0.7
    max_tokens: 2000
    top_p: 0.9
    stop_sequences: []
    
  # 百度千帆(文心一言)配置
  qianfan:
    ak: "your-ak"
    sk: "your-sk"
    
  # 智谱AI(ChatGLM)配置
  zhipuai:
    api_key: "your-api-key"
    model: "glm-4"
    
  # 讯飞星火配置
  spark:
    app_id: "your-app-id"
    api_key: "your-api-key"
    api_secret: "your-api-secret"
    
  # 百川配置
  baichuan:
    api_key: "your-api-key"
    
  # 通用配置
  common:
    temperature: 0.7
    top_p: 0.9
    max_tokens: 2000
    presence_penalty: 0
    frequency_penalty: 0
    
  # 流式响应配置
  stream:
    enabled: true
    chunk_size: 20
    
  # 重试配置
  retry:
    max_retries: 3
    retry_interval: 1  # 秒
    
  # 超时配置
  timeout:
    connect: 10  # 秒
    read: 30    # 秒 